apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
  namespace: default
spec:
  selector:
    matchLabels:
      app: website
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: website-1.1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: config-volume
        configMap:
          name: website-1